### ISSUE TITLE
Update new paper 

### ISSUE THREAD

**Issue by ShenghaiRong** [Qinying-Liu/Awesome-Open-Vocabulary-Semantic-Segmentation#1]
[Exploring Open-Vocabulary Semantic Segmentation from CLIP Vision Encoder Distillation Only](https://openaccess.thecvf.com/content/ICCV2023/html/Chen_Exploring_Open-Vocabulary_Semantic_Segmentation_from_CLIP_Vision_Encoder_Distillation_Only_ICCV_2023_paper.html)
[Open-Vocabulary Semantic Segmentation with Decoupled One-Pass Network](https://openaccess.thecvf.com/content/ICCV2023/papers/Han_Open-Vocabulary_Semantic_Segmentation_with_Decoupled_One-Pass_Network_ICCV_2023_paper.pdf)

**Comment by Qinying-Liu** [comment]
Thanks!
